### ISSUE TITLE
Plugin failed to decode

### ISSUE THREAD

**Issue by vipau** [Yethal/nu_plugin_hcl#1]
When trying to 'register' the plugin, I get:

> Plugin failed to decode: invalid type: string "provider", expected a sequence

Is this my fault, or is this in the plugin source? Cheers

**Comment by Yethal** [comment]
Can you provide output of `version|transpose key value|to md` ?

**Comment by vipau** [comment]
@Yethal 

|key|value|
|-|-|
|version|0.87.1|
|branch||
|commit_hash||
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew)|
|cargo_version|cargo 1.74.0|
|build_time|2023-11-18 17:46:36 +00:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, sqlite, trash, which, zip|
|installed_plugins||

**Comment by Yethal** [comment]
Plugin code requres update to be compatible with 0.87.1
